apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true

  - name: Postgres
    uid: postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: tgassistant
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: tgassistant
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
