using Microsoft.Extensions.DependencyInjection;
using TgAssistant.Core.Interfaces;
using TgAssistant.Host.Launch;
using TgAssistant.Host.Stage6Ab;
using TgAssistant.Host.Stage5Repair;
using TgAssistant.Infrastructure.Database;
using TgAssistant.Intelligence.Stage5;
using TgAssistant.Intelligence.Stage6;
using TgAssistant.Intelligence.Stage6.Clarification;
using TgAssistant.Intelligence.Stage6.CompetingContext;
using TgAssistant.Intelligence.Stage6.Control;
using TgAssistant.Intelligence.Stage6.CurrentState;
using TgAssistant.Intelligence.Stage6.DraftReview;
using TgAssistant.Intelligence.Stage6.Drafts;
using TgAssistant.Intelligence.Stage6.Network;
using TgAssistant.Intelligence.Stage6.Outcome;
using TgAssistant.Intelligence.Stage6.Periodization;
using TgAssistant.Intelligence.Stage6.Profiles;
using TgAssistant.Intelligence.Stage6.Strategy;
using TgAssistant.Processing.Archive;
using TgAssistant.Processing.Archive.ExternalIngestion;
using TgAssistant.Telegram.Bot;
using TgAssistant.Web.Read;

namespace TgAssistant.Host.Startup;

public static partial class ServiceRegistrationExtensions
{
    public static IServiceCollection AddTelegramAssistantDomainServices(this IServiceCollection services)
    {
        services.AddSingleton<IMessageRepository, MessageRepository>();
        services.AddSingleton<IArchiveImportRepository, ArchiveImportRepository>();
        services.AddSingleton<IStickerCacheRepository, StickerCacheRepository>();
        services.AddSingleton<IPromptTemplateRepository, PromptTemplateRepository>();
        services.AddSingleton<IAnalysisStateRepository, AnalysisStateRepository>();
        services.AddSingleton<IMessageExtractionRepository, MessageExtractionRepository>();
        services.AddSingleton<IIntelligenceRepository, IntelligenceRepository>();
        services.AddSingleton<IExtractionErrorRepository, ExtractionErrorRepository>();
        services.AddSingleton<IEntityRepository, EntityRepository>();
        services.AddSingleton<IEntityAliasRepository, EntityAliasRepository>();
        services.AddSingleton<IEntityMergeRepository, EntityMergeRepository>();
        services.AddSingleton<IEntityMergeCommandRepository, EntityMergeCommandRepository>();
        services.AddSingleton<IStage5MetricsRepository, Stage5MetricsRepository>();
        services.AddSingleton<IAnalysisUsageRepository, AnalysisUsageRepository>();
        services.AddSingleton<ICommunicationEventRepository, CommunicationEventRepository>();
        services.AddSingleton<IEmbeddingRepository, EmbeddingRepository>();
        services.AddSingleton<IMaintenanceRepository, MaintenanceRepository>();
        services.AddSingleton<IFactReviewCommandRepository, FactReviewCommandRepository>();
        services.AddSingleton<IFactRepository, FactRepository>();
        services.AddSingleton<IRelationshipRepository, RelationshipRepository>();
        services.AddSingleton<ISummaryRepository, SummaryRepository>();
        services.AddSingleton<IChatDialogSummaryRepository, ChatDialogSummaryRepository>();
        services.AddSingleton<IChatSessionRepository, ChatSessionRepository>();
        services.AddSingleton<IPeriodRepository, PeriodRepository>();
        services.AddSingleton<IClarificationRepository, ClarificationRepository>();
        services.AddSingleton<IOfflineEventRepository, OfflineEventRepository>();
        services.AddSingleton<IStateProfileRepository, StateProfileRepository>();
        services.AddSingleton<IStrategyDraftRepository, StrategyDraftRepository>();
        services.AddSingleton<IInboxConflictRepository, InboxConflictRepository>();
        services.AddSingleton<IDependencyLinkRepository, DependencyLinkRepository>();
        services.AddSingleton<IDomainReviewEventRepository, DomainReviewEventRepository>();
        services.AddSingleton<IBudgetOpsRepository, BudgetOpsRepository>();
        services.AddSingleton<IEvalRepository, EvalRepository>();
        services.AddSingleton<IExternalArchiveIngestionRepository, ExternalArchiveIngestionRepository>();
        services.AddSingleton<IChatCoordinationService, ChatCoordinationService>();
        services.AddSingleton<FoundationDomainVerificationService>();
        services.AddSingleton<IClarificationAnswerApplier, ClarificationAnswerApplier>();
        services.AddSingleton<IClarificationDependencyResolver, ClarificationDependencyResolver>();
        services.AddSingleton<IRecomputeTargetPlanner, RecomputeTargetPlanner>();
        services.AddSingleton<IClarificationOrchestrator, ClarificationOrchestrator>();
        services.AddSingleton<ClarificationOrchestrationVerificationService>();
        services.AddSingleton<IPeriodBoundaryDetector, PeriodBoundaryDetector>();
        services.AddSingleton<ITimelineAssembler, TimelineAssembler>();
        services.AddSingleton<ITransitionBuilder, TransitionBuilder>();
        services.AddSingleton<IPeriodEvidenceAssembler, PeriodEvidenceAssembler>();
        services.AddSingleton<IPeriodProposalService, PeriodProposalService>();
        services.AddSingleton<IPeriodizationService, PeriodizationService>();
        services.AddSingleton<PeriodizationVerificationService>();
        services.AddSingleton<IStateScoreCalculator, StateScoreCalculator>();
        services.AddSingleton<IStateConfidenceEvaluator, StateConfidenceEvaluator>();
        services.AddSingleton<IDynamicLabelMapper, DynamicLabelMapper>();
        services.AddSingleton<IRelationshipStatusMapper, RelationshipStatusMapper>();
        services.AddSingleton<ICurrentStateEngine, CurrentStateEngine>();
        services.AddSingleton<StateEngineVerificationService>();
        services.AddSingleton<IProfileTraitExtractor, ProfileTraitExtractor>();
        services.AddSingleton<IPairProfileSynthesizer, PairProfileSynthesizer>();
        services.AddSingleton<IProfileConfidenceEvaluator, ProfileConfidenceEvaluator>();
        services.AddSingleton<IPatternSynthesisService, PatternSynthesisService>();
        services.AddSingleton<IProfileEngine, ProfileEngine>();
        services.AddSingleton<ProfileEngineVerificationService>();
        services.AddSingleton<IStrategyOptionGenerator, StrategyOptionGenerator>();
        services.AddSingleton<IStrategyRiskEvaluator, StrategyRiskEvaluator>();
        services.AddSingleton<IStrategyRanker, StrategyRanker>();
        services.AddSingleton<IStrategyConfidenceEvaluator, StrategyConfidenceEvaluator>();
        services.AddSingleton<IMicroStepPlanner, MicroStepPlanner>();
        services.AddSingleton<IStrategyEngine, StrategyEngine>();
        services.AddSingleton<StrategyEngineVerificationService>();
        services.AddSingleton<IDraftGenerator, DraftGenerator>();
        services.AddSingleton<IDraftStyleAdapter, DraftStyleAdapter>();
        services.AddSingleton<IDraftStrategyChecker, DraftStrategyChecker>();
        services.AddSingleton<IDraftPackagingService, DraftPackagingService>();
        services.AddSingleton<IDraftEngine, DraftEngine>();
        services.AddSingleton<DraftEngineVerificationService>();
        services.AddSingleton<IDraftRiskAssessor, DraftRiskAssessor>();
        services.AddSingleton<IDraftStrategyFitChecker, DraftStrategyFitChecker>();
        services.AddSingleton<ISaferRewriteGenerator, SaferRewriteGenerator>();
        services.AddSingleton<INaturalRewriteGenerator, NaturalRewriteGenerator>();
        services.AddSingleton<IDraftReviewEngine, DraftReviewEngine>();
        services.AddSingleton<DraftReviewVerificationService>();
        services.AddSingleton<IBotCommandService, BotCommandService>();
        services.AddSingleton<BotCommandVerificationService>();
        services.AddSingleton<IWebReadService, WebReadService>();
        services.AddSingleton<IWebReviewService, WebReviewService>();
        services.AddSingleton<IWebOpsService, WebOpsService>();
        services.AddSingleton<IWebSearchService, WebSearchService>();
        services.AddSingleton<IWebRouteRenderer, WebRouteRenderer>();
        services.AddSingleton<WebReadVerificationService>();
        services.AddSingleton<WebReviewVerificationService>();
        services.AddSingleton<WebOpsVerificationService>();
        services.AddSingleton<WebSearchVerificationService>();
        services.AddSingleton<INodeRoleResolver, NodeRoleResolver>();
        services.AddSingleton<IInfluenceEdgeBuilder, InfluenceEdgeBuilder>();
        services.AddSingleton<IInformationFlowBuilder, InformationFlowBuilder>();
        services.AddSingleton<INetworkScoringService, NetworkScoringService>();
        services.AddSingleton<INetworkGraphService, NetworkGraphService>();
        services.AddSingleton<NetworkVerificationService>();
        services.AddSingleton<IDraftActionMatcher, DraftActionMatcher>();
        services.AddSingleton<IObservedOutcomeRecorder, ObservedOutcomeRecorder>();
        services.AddSingleton<ILearningSignalBuilder, LearningSignalBuilder>();
        services.AddSingleton<IOutcomeService, OutcomeService>();
        services.AddSingleton<OutcomeVerificationService>();
        services.AddSingleton<IBudgetGuardrailService, BudgetGuardrailService>();
        services.AddSingleton<IEvalHarnessService, EvalHarnessService>();
        services.AddSingleton<BudgetVerificationService>();
        services.AddSingleton<EvalVerificationService>();
        services.AddSingleton<LaunchReadinessVerificationService>();
        services.AddSingleton<Stage5ScopedRepairCommand>();
        services.AddSingleton<Stage6LightAbRunCommand>();
        services.AddSingleton<IExternalArchiveImportContractValidator, ExternalArchiveImportContractValidator>();
        services.AddSingleton<IExternalArchiveProvenanceWeightingService, ExternalArchiveProvenanceWeightingService>();
        services.AddSingleton<IExternalArchiveLinkagePlanner, ExternalArchiveLinkagePlanner>();
        services.AddSingleton<IExternalArchivePreparationService, ExternalArchivePreparationService>();
        services.AddSingleton<IExternalArchiveIngestionService, ExternalArchiveIngestionService>();
        services.AddSingleton<ExternalArchiveVerificationService>();
        services.AddSingleton<ICompetingContextInterpretationService, CompetingContextInterpretationService>();
        services.AddSingleton<ICompetingContextRuntimeService, CompetingContextRuntimeService>();
        services.AddSingleton<CompetingContextVerificationService>();

        services.AddSingleton<ExtractionSchemaValidator>();
        services.AddSingleton<MessageContentBuilder>();
        services.AddSingleton<AnalysisContextBuilder>();
        services.AddSingleton<SummaryHistoricalRetrievalService>();
        services.AddSingleton<Stage5VerificationService>();
        services.AddSingleton<ExtractionApplier>();
        services.AddSingleton<ExpensivePassResolver>();
        services.AddSingleton<IBotChatService, BotChatService>();
        services.AddSingleton<TelegramDesktopArchiveParser>();

        return services;
    }
}
